# Generated by Django 5.2.7 on 2025-11-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_receta', models.CharField(max_length=30)),
                ('utensilios', models.TextField(max_length=2000)),
                ('ingredientes', models.TextField(max_length=8000)),
                ('procedimiento', models.TextField(max_length=8000)),
            ],
        ),
    ]
