# Generated by Django 5.2.7 on 2025-11-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='descripcion',
            field=models.CharField(default='Una deliciosa receta para ti.', max_length=150),
            preserve_default=False,
        ),
    ]
