# Generated by Django 5.2.7 on 2025-11-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0002_receta_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='image',
            field=models.ImageField(null=True, upload_to='recetas'),
        ),
    ]
