recetas = {
    "Pechuga con Crema de Chipotle" : 
        {"tiempo" : "15 mins",
         "descripcion" : "Una receta básica para tus comidas diarias: Pechuga de pollo en crema de chipotle preparado con Carnation y Media Crema Nestlé",
         "utensilios" : {"tarro", "cuchara", "licuadora"},
         "ingredientes" : {"1 lata de leche evaporada", 
                           "1 lata de media crema", 
                           "1 paquete de queso crema", 
                           "1 taza de agua", 
                           "1 cucharada de consomé", 
                           "1 cucharada de consomé de pollo", 
                           "1 cucharada de sal con ajo", 
                           "2 chiles chipotles adobados", 
                           "¾ de taza de puré de tomate natural",
                           "4 pechugas de pollo cocidas y fritas",
                           "5 ramas de perejil"},
        "procedimiento" : {"Licúa la leche evaporada y la media crema, el queso crema, el agua, el consomé, la sal y el chipotle",
                           "Calienta el puré de tomate hasta que cambie de color, agrega lo licuado y cocina hasta que espese",
                           "Sirve el pollo con la salsa y decora con el perejil"}},

    "Enchiladas Verdes" :
        {"tiempo" : "25 mins",
         "descripcion" : "Clásicas enchiladas mexicanas bañadas en salsa verde, rellenas de pollo y cubiertas con crema y queso.",
         "utensilios" : {"cazuela", "licuadora", "sartén"},
         "ingredientes" : {"10 tortillas de maíz",
                           "2 pechugas de pollo cocidas y desmenuzadas",
                           "1 taza de crema",
                           "½ taza de queso rallado",
                           "5 tomates verdes",
                           "1 diente de ajo",
                           "1 trozo de cebolla",
                           "1 chile serrano",
                           "1 taza de caldo de pollo",
                           "1 cucharada de aceite",
                           "sal al gusto"},
         "procedimiento" : {"Cuece los tomates, el ajo, la cebolla y el chile hasta que cambien de color",
                            "Licúa con el caldo de pollo y un poco de sal",
                            "Fríe la salsa en una cazuela por 5 minutos",
                            "Calienta las tortillas, rellénalas de pollo y báñalas con la salsa caliente",
                            "Decora con crema y queso rallado"}},

    "Tacos de Bistec" :
        {"tiempo" : "20 mins",
         "descripcion" : "Tacos tradicionales de bistec con cebolla, cilantro y un toque de limón, perfectos para cualquier antojo.",
         "utensilios" : {"sartén", "tabla para picar", "cuchillo"},
         "ingredientes" : {"½ kilo de bistec de res en trozos",
                           "1 cebolla picada",
                           "½ taza de cilantro picado",
                           "8 tortillas de maíz",
                           "2 limones",
                           "sal y pimienta al gusto",
                           "aceite para freír"},
         "procedimiento" : {"Sazona el bistec con sal y pimienta",
                            "Calienta el aceite y fríe la carne hasta dorar",
                            "Agrega la cebolla y cocina un minuto más",
                            "Sirve en tortillas calientes y acompaña con cilantro y limón"}},

    "Spaghetti a la Boloñesa" :
        {"tiempo" : "30 mins",
         "descripcion" : "Un clásico italiano con carne molida y salsa de tomate, ideal para una comida casera y reconfortante.",
         "utensilios" : {"olla", "sartén", "cuchara de madera"},
         "ingredientes" : {"250 g de spaghetti",
                           "300 g de carne molida de res",
                           "2 tazas de puré de tomate",
                           "1 diente de ajo picado",
                           "½ cebolla picada",
                           "2 cucharadas de aceite de oliva",
                           "sal y orégano al gusto"},
         "procedimiento" : {"Cuece la pasta según las instrucciones del paquete",
                            "Fríe la cebolla y el ajo hasta acitronar, agrega la carne y cocina hasta dorar",
                            "Incorpora el puré de tomate y el orégano, deja cocinar 10 minutos",
                            "Sirve la pasta con la salsa encima"}},

    "Arroz a la Mexicana" :
        {"tiempo" : "25 mins",
         "descripcion" : "El acompañamiento por excelencia: arroz rojo con jitomate, chícharos y zanahoria.",
         "utensilios" : {"olla", "cuchara de madera", "licuadora"},
         "ingredientes" : {"1 taza de arroz",
                           "2 jitomates",
                           "¼ de cebolla",
                           "1 diente de ajo",
                           "2 tazas de caldo de pollo",
                           "½ taza de chícharos y zanahorias",
                           "2 cucharadas de aceite",
                           "sal al gusto"},
         "procedimiento" : {"Licúa el jitomate, la cebolla y el ajo con el caldo",
                            "Fríe el arroz en aceite hasta dorar ligeramente",
                            "Agrega lo licuado, sazona con sal y cocina tapado hasta que el líquido se absorba",
                            "Añade los chícharos y zanahorias, mezcla y deja reposar"}},

    "Chilaquiles Rojos con Pollo" :
        {"tiempo" : "20 mins",
         "descripcion" : "Totopos bañados en salsa roja, con pollo desmenuzado, crema, queso y cebolla, perfectos para el desayuno.",
         "utensilios" : {"cazuela", "licuadora", "sartén"},
         "ingredientes" : {"10 tortillas cortadas en triángulos y fritas",
                           "2 jitomates",
                           "2 chiles guajillos",
                           "¼ de cebolla",
                           "1 diente de ajo",
                           "½ taza de crema",
                           "½ taza de queso rallado",
                           "1 pechuga de pollo cocida y desmenuzada",
                           "aceite y sal al gusto"},
         "procedimiento" : {"Hierve los jitomates, chiles, cebolla y ajo, luego licúa con un poco de agua y sal",
                            "Fríe la salsa en una cazuela por 5 minutos",
                            "Agrega los totopos y mezcla hasta que se suavicen ligeramente",
                            "Sirve con pollo, crema y queso"}},

    "Sopa de Fideo" : 
        {"tiempo" : "20 mins",
         "descripcion" : "Una sopa casera y reconfortante, con fideos dorados en caldillo de jitomate.",
         "utensilios" : {"olla", "licuadora", "cuchara de madera"},
         "ingredientes" : {"1 taza de fideo delgado",
                           "2 jitomates",
                           "¼ de cebolla",
                           "1 diente de ajo",
                           "3 tazas de caldo de pollo",
                           "2 cucharadas de aceite",
                           "sal al gusto"},
         "procedimiento" : {"Fríe el fideo en aceite hasta que dore ligeramente",
                            "Licúa jitomate, cebolla y ajo con un poco de caldo",
                            "Agrega al fideo y cocina 2 minutos",
                            "Añade el resto del caldo y cuece hasta que el fideo esté suave"}},

    "Papas al Horno con Queso" :
        {"tiempo" : "30 mins",
         "descripcion" : "Papas gratinadas con crema y queso, ideales como guarnición o plato principal.",
         "utensilios" : {"horno", "cazuela", "cuchillo"},
         "ingredientes" : {"4 papas grandes en rodajas",
                           "1 taza de crema",
                           "1 taza de queso rallado",
                           "½ taza de leche",
                           "sal y pimienta al gusto"},
         "procedimiento" : {"Precalienta el horno a 180°C",
                            "Coloca las papas en un refractario, salpica sal y pimienta",
                            "Cubre con crema, leche y queso",
                            "Hornea por 25 minutos o hasta gratinar"}},

    "Huevos a la Mexicana" :
        {"tiempo" : "10 mins",
         "descripcion" : "Clásicos huevos revueltos con jitomate, cebolla y chile, perfectos para el desayuno.",
         "utensilios" : {"sartén", "cuchara", "tabla para picar"},
         "ingredientes" : {"3 huevos",
                           "1 jitomate picado",
                           "¼ de cebolla picada",
                           "1 chile verde picado",
                           "1 cucharada de aceite",
                           "sal al gusto"},
         "procedimiento" : {"Fríe jitomate, cebolla y chile en aceite por 2 minutos",
                            "Agrega los huevos y mezcla hasta cocer",
                            "Sazona con sal y sirve caliente"}},

    "Quesadillas de Flor de Calabaza" :
        {"tiempo" : "15 mins",
         "descripcion" : "Quesadillas tradicionales con flor de calabaza, queso y epazote, hechas al comal.",
         "utensilios" : {"comal", "cuchillo", "espátula"},
         "ingredientes" : {"8 tortillas de maíz",
                           "1 taza de flor de calabaza picada",
                           "½ taza de queso Oaxaca o manchego",
                           "2 ramas de epazote",
                           "aceite o mantequilla"},
         "procedimiento" : {"Sofríe la flor y el epazote por 2 minutos",
                            "Coloca sobre una tortilla, agrega queso y tapa con otra",
                            "Calienta en el comal hasta que el queso derrita"}},

    "Pozole Rojo" :
        {"tiempo" : "2 hrs",
         "descripcion" : "Un clásico platillo mexicano de maíz hominy con carne de cerdo y chile rojo.",
         "utensilios" : {"olla grande", "licuadora", "cuchillo"},
         "ingredientes" : {"1 kilo de carne de cerdo en trozos",
                           "500 g de maíz para pozole precocido",
                           "5 chiles guajillos",
                           "2 dientes de ajo",
                           "¼ de cebolla",
                           "sal al gusto",
                           "agua suficiente"},
         "procedimiento" : {"Cocina la carne y el maíz juntos hasta que ablanden",
                            "Hierve los chiles, ajo y cebolla; licúa con un poco de agua",
                            "Agrega la salsa colada a la olla, sazona y cocina 30 minutos más",
                            "Sirve con lechuga, rábano, orégano y limón"}},

    "Tostadas de Atún" :
        {"tiempo" : "10 mins",
         "descripcion" : "Frescas tostadas con atún, jitomate y aguacate, perfectas para una comida ligera.",
         "utensilios" : {"tazón", "cuchillo", "cuchara"},
         "ingredientes" : {"1 lata de atún en agua",
                           "1 jitomate picado",
                           "¼ de cebolla picada",
                           "1 cucharada de mayonesa",
                           "1 aguacate",
                           "4 tostadas"},
         "procedimiento" : {"Mezcla el atún, jitomate, cebolla y mayonesa",
                            "Coloca sobre las tostadas",
                            "Agrega rebanadas de aguacate por encima"}},

    "Empanadas de Frijol" :
        {"tiempo" : "25 mins",
         "descripcion" : "Crujientes empanadas rellenas de frijoles refritos, típicas del sur de México.",
         "utensilios" : {"sartén", "rodillo", "cuchara"},
         "ingredientes" : {"2 tazas de masa para tortillas",
                           "1 taza de frijoles refritos",
                           "aceite para freír",
                           "sal al gusto"},
         "procedimiento" : {"Toma porciones de masa y extiende con el rodillo",
                            "Agrega una cucharada de frijoles, dobla y sella las orillas",
                            "Fríe en aceite caliente hasta que doren"}},

    "Pescado Empapelado" :
        {"tiempo" : "30 mins",
         "descripcion" : "Filete de pescado cocido al vapor en papel aluminio con verduras y limón.",
         "utensilios" : {"horno", "cuchillo", "papel aluminio"},
         "ingredientes" : {"2 filetes de pescado blanco",
                           "1 jitomate en rodajas",
                           "½ cebolla en rodajas",
                           "½ pimiento en tiras",
                           "1 limón en rodajas",
                           "sal y pimienta al gusto"},
         "procedimiento" : {"Coloca el pescado sobre el aluminio y añade las verduras y limón",
                            "Sazona con sal y pimienta",
                            "Cierra el papel y hornea 20 minutos a 180°C"}},

    "Guacamole Casero" :
        {"tiempo" : "10 mins",
         "descripcion" : "El acompañamiento mexicano por excelencia, hecho con aguacate, limón y chile.",
         "utensilios" : {"tazón", "tenedor", "cuchillo"},
         "ingredientes" : {"2 aguacates maduros",
                           "1 jitomate picado",
                           "¼ de cebolla picada",
                           "1 chile verde picado",
                           "jugo de 1 limón",
                           "sal al gusto"},
         "procedimiento" : {"Machaca los aguacates con un tenedor",
                            "Agrega el resto de los ingredientes y mezcla bien",
                            "Sirve inmediatamente con totopos"}},

    "Calabacitas con Elote" :
        {"tiempo" : "20 mins",
         "descripcion" : "Un guisado ligero y saludable con calabacitas, granos de elote y crema.",
         "utensilios" : {"cazuela", "cuchillo", "cuchara de madera"},
         "ingredientes" : {"3 calabacitas en cubos",
                           "1 taza de granos de elote",
                           "½ taza de crema",
                           "¼ de cebolla picada",
                           "1 diente de ajo picado",
                           "1 cucharada de aceite",
                           "sal al gusto"},
         "procedimiento" : {"Sofríe cebolla y ajo en aceite",
                            "Agrega calabacitas y elote, cocina por 5 minutos",
                            "Incorpora la crema, sazona y cocina 5 minutos más"}}
}
